checks:
  return-statements:
    enabled: true
    config:
      threshold: 8
  method-complexity:
    enabled: true
    config:
      threshold: 32
  similar-code:
    enabled: false
exclude_patterns:
  - "**/*_string.go"
  - "**/*_test.go"
  - "**/*_gen.go"
