language: go
sudo: false

go:
  - 1.21.x

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - make test
  - go test -coverprofile c.tmp ./...
  - grep -v "_string.go" c.tmp > c.out
  - rm c.tmp

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
